// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: address/address.proto

package address

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Province      string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PostalCode    string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressResponse) Reset() {
	*x = AddressResponse{}
	mi := &file_address_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressResponse) ProtoMessage() {}

func (x *AddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_address_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressResponse.ProtoReflect.Descriptor instead.
func (*AddressResponse) Descriptor() ([]byte, []int) {
	return file_address_address_proto_rawDescGZIP(), []int{0}
}

func (x *AddressResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddressResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddressResponse) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *AddressResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressResponse) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ProvinceId    uint64                 `protobuf:"varint,2,opt,name=province_id,json=provinceId,proto3" json:"province_id,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PostalCode    string                 `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_address_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_address_address_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRequest) GetProvinceId() uint64 {
	if x != nil {
		return x.ProvinceId
	}
	return 0
}

func (x *CreateRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_address_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_address_address_proto_rawDescGZIP(), []int{2}
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*AddressResponse     `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_address_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_address_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_address_address_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllResponse) GetAddresses() []*AddressResponse {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type GetOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneRequest) Reset() {
	*x = GetOneRequest{}
	mi := &file_address_address_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRequest) ProtoMessage() {}

func (x *GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_address_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneRequest.ProtoReflect.Descriptor instead.
func (*GetOneRequest) Descriptor() ([]byte, []int) {
	return file_address_address_proto_rawDescGZIP(), []int{4}
}

func (x *GetOneRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	ProvinceId    *uint64                `protobuf:"varint,3,opt,name=province_id,json=provinceId,proto3,oneof" json:"province_id,omitempty"`
	City          *string                `protobuf:"bytes,4,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Address       *string                `protobuf:"bytes,5,opt,name=address,proto3,oneof" json:"address,omitempty"`
	PostalCode    *string                `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3,oneof" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_address_address_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_address_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_address_address_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateRequest) GetProvinceId() uint64 {
	if x != nil && x.ProvinceId != nil {
		return *x.ProvinceId
	}
	return 0
}

func (x *UpdateRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdateRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *UpdateRequest) GetPostalCode() string {
	if x != nil && x.PostalCode != nil {
		return *x.PostalCode
	}
	return ""
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_address_address_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_address_address_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_address_address_proto_rawDescGZIP(), []int{6}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_address_address_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_address_address_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_address_address_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_address_address_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_address_address_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_address_address_proto_rawDescGZIP(), []int{8}
}

var File_address_address_proto protoreflect.FileDescriptor

const file_address_address_proto_rawDesc = "" +
	"\n" +
	"\x15address/address.proto\x12\aaddress\"\xa2\x01\n" +
	"\x0fAddressResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bprovince\x18\x03 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x1f\n" +
	"\vpostal_code\x18\x06 \x01(\tR\n" +
	"postalCode\"\x95\x01\n" +
	"\rCreateRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1f\n" +
	"\vprovince_id\x18\x02 \x01(\x04R\n" +
	"provinceId\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x1f\n" +
	"\vpostal_code\x18\x05 \x01(\tR\n" +
	"postalCode\"\x0f\n" +
	"\rGetAllRequest\"H\n" +
	"\x0eGetAllResponse\x126\n" +
	"\taddresses\x18\x01 \x03(\v2\x18.address.AddressResponseR\taddresses\"\x1f\n" +
	"\rGetOneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xfd\x01\n" +
	"\rUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12$\n" +
	"\vprovince_id\x18\x03 \x01(\x04H\x01R\n" +
	"provinceId\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x04 \x01(\tH\x02R\x04city\x88\x01\x01\x12\x1d\n" +
	"\aaddress\x18\x05 \x01(\tH\x03R\aaddress\x88\x01\x01\x12$\n" +
	"\vpostal_code\x18\x06 \x01(\tH\x04R\n" +
	"postalCode\x88\x01\x01B\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_province_idB\a\n" +
	"\x05_cityB\n" +
	"\n" +
	"\b_addressB\x0e\n" +
	"\f_postal_code\"\x10\n" +
	"\x0eUpdateResponse\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x10\n" +
	"\x0eDeleteResponse2\xb9\x02\n" +
	"\x0eAddressService\x12:\n" +
	"\x06Create\x12\x16.address.CreateRequest\x1a\x18.address.AddressResponse\x129\n" +
	"\x06GetAll\x12\x16.address.GetAllRequest\x1a\x17.address.GetAllResponse\x12:\n" +
	"\x06GetOne\x12\x16.address.GetOneRequest\x1a\x18.address.AddressResponse\x129\n" +
	"\x06Update\x12\x16.address.UpdateRequest\x1a\x17.address.UpdateResponse\x129\n" +
	"\x06Delete\x12\x16.address.DeleteRequest\x1a\x17.address.DeleteResponseB\x1aZ\x18shop/internal/pb/addressb\x06proto3"

var (
	file_address_address_proto_rawDescOnce sync.Once
	file_address_address_proto_rawDescData []byte
)

func file_address_address_proto_rawDescGZIP() []byte {
	file_address_address_proto_rawDescOnce.Do(func() {
		file_address_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_address_address_proto_rawDesc), len(file_address_address_proto_rawDesc)))
	})
	return file_address_address_proto_rawDescData
}

var file_address_address_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_address_address_proto_goTypes = []any{
	(*AddressResponse)(nil), // 0: address.AddressResponse
	(*CreateRequest)(nil),   // 1: address.CreateRequest
	(*GetAllRequest)(nil),   // 2: address.GetAllRequest
	(*GetAllResponse)(nil),  // 3: address.GetAllResponse
	(*GetOneRequest)(nil),   // 4: address.GetOneRequest
	(*UpdateRequest)(nil),   // 5: address.UpdateRequest
	(*UpdateResponse)(nil),  // 6: address.UpdateResponse
	(*DeleteRequest)(nil),   // 7: address.DeleteRequest
	(*DeleteResponse)(nil),  // 8: address.DeleteResponse
}
var file_address_address_proto_depIdxs = []int32{
	0, // 0: address.GetAllResponse.addresses:type_name -> address.AddressResponse
	1, // 1: address.AddressService.Create:input_type -> address.CreateRequest
	2, // 2: address.AddressService.GetAll:input_type -> address.GetAllRequest
	4, // 3: address.AddressService.GetOne:input_type -> address.GetOneRequest
	5, // 4: address.AddressService.Update:input_type -> address.UpdateRequest
	7, // 5: address.AddressService.Delete:input_type -> address.DeleteRequest
	0, // 6: address.AddressService.Create:output_type -> address.AddressResponse
	3, // 7: address.AddressService.GetAll:output_type -> address.GetAllResponse
	0, // 8: address.AddressService.GetOne:output_type -> address.AddressResponse
	6, // 9: address.AddressService.Update:output_type -> address.UpdateResponse
	8, // 10: address.AddressService.Delete:output_type -> address.DeleteResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_address_address_proto_init() }
func file_address_address_proto_init() {
	if File_address_address_proto != nil {
		return
	}
	file_address_address_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_address_address_proto_rawDesc), len(file_address_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_address_address_proto_goTypes,
		DependencyIndexes: file_address_address_proto_depIdxs,
		MessageInfos:      file_address_address_proto_msgTypes,
	}.Build()
	File_address_address_proto = out.File
	file_address_address_proto_goTypes = nil
	file_address_address_proto_depIdxs = nil
}
