mysql:
  max_life_time: 180
  max_open_conns: 10
  max_idle_conns: 10

auth_service:
  # 60 * 15 -> 15 Minutes
  access_token_duration: 60m
  # 60 * 60 * 24 * 30 -> 30 days 
  refresh_token_duration: 720h
  # 60 * 2 -> 2 Minutes 
  otp_code_duration: 2m

upload:
  max_dimension: 512