// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: product/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         uint64                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         *uint64                `protobuf:"varint,5,opt,name=stock,proto3,oneof" json:"stock,omitempty"`
	CategoryId    uint64                 `protobuf:"varint,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	MainImage     []byte                 `protobuf:"bytes,7,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductMetadata) Reset() {
	*x = ProductMetadata{}
	mi := &file_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductMetadata) ProtoMessage() {}

func (x *ProductMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductMetadata.ProtoReflect.Descriptor instead.
func (*ProductMetadata) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductMetadata) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProductMetadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductMetadata) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductMetadata) GetStock() uint64 {
	if x != nil && x.Stock != nil {
		return *x.Stock
	}
	return 0
}

func (x *ProductMetadata) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductMetadata) GetMainImage() []byte {
	if x != nil {
		return x.MainImage
	}
	return nil
}

type GalleryImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         []byte                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GalleryImage) Reset() {
	*x = GalleryImage{}
	mi := &file_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GalleryImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GalleryImage) ProtoMessage() {}

func (x *GalleryImage) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GalleryImage.ProtoReflect.Descriptor instead.
func (*GalleryImage) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *GalleryImage) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*CreateRequest_Metadata
	//	*CreateRequest_Image
	Payload       isCreateRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRequest) GetPayload() isCreateRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CreateRequest) GetMetadata() *ProductMetadata {
	if x != nil {
		if x, ok := x.Payload.(*CreateRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *CreateRequest) GetImage() *GalleryImage {
	if x != nil {
		if x, ok := x.Payload.(*CreateRequest_Image); ok {
			return x.Image
		}
	}
	return nil
}

type isCreateRequest_Payload interface {
	isCreateRequest_Payload()
}

type CreateRequest_Metadata struct {
	Metadata *ProductMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type CreateRequest_Image struct {
	Image *GalleryImage `protobuf:"bytes,2,opt,name=image,proto3,oneof"`
}

func (*CreateRequest_Metadata) isCreateRequest_Payload() {}

func (*CreateRequest_Image) isCreateRequest_Payload() {}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         uint64                 `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         uint64                 `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	CategoryId    uint64                 `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	MainImage     string                 `protobuf:"bytes,8,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	Images        []string               `protobuf:"bytes,9,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProductResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductResponse) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductResponse) GetStock() uint64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductResponse) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductResponse) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

func (x *ProductResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	CategorySlug  *string                `protobuf:"bytes,3,opt,name=category_slug,json=categorySlug,proto3,oneof" json:"category_slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllRequest) GetCategorySlug() string {
	if x != nil && x.CategorySlug != nil {
		return *x.CategorySlug
	}
	return ""
}

type ProductListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Price         uint64                 `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock         uint64                 `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	CategoryId    uint64                 `protobuf:"varint,6,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	MainImage     string                 `protobuf:"bytes,7,opt,name=main_image,json=mainImage,proto3" json:"main_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductListItem) Reset() {
	*x = ProductListItem{}
	mi := &file_product_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductListItem) ProtoMessage() {}

func (x *ProductListItem) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductListItem.ProtoReflect.Descriptor instead.
func (*ProductListItem) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{5}
}

func (x *ProductListItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductListItem) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProductListItem) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductListItem) GetStock() uint64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *ProductListItem) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductListItem) GetMainImage() string {
	if x != nil {
		return x.MainImage
	}
	return ""
}

type PaginationMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationMeta) Reset() {
	*x = PaginationMeta{}
	mi := &file_product_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationMeta) ProtoMessage() {}

func (x *PaginationMeta) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationMeta.ProtoReflect.Descriptor instead.
func (*PaginationMeta) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{6}
}

func (x *PaginationMeta) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationMeta) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationMeta) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PaginationMeta) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductListItem     `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Meta          *PaginationMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_product_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllResponse) GetProducts() []*ProductListItem {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *GetAllResponse) GetMeta() *PaginationMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetOneBySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneBySlugRequest) Reset() {
	*x = GetOneBySlugRequest{}
	mi := &file_product_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneBySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneBySlugRequest) ProtoMessage() {}

func (x *GetOneBySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneBySlugRequest.ProtoReflect.Descriptor instead.
func (*GetOneBySlugRequest) Descriptor() ([]byte, []int) {
	return file_product_product_proto_rawDescGZIP(), []int{8}
}

func (x *GetOneBySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

var File_product_product_proto protoreflect.FileDescriptor

const file_product_product_proto_rawDesc = "" +
	"\n" +
	"\x15product/product.proto\x12\aproduct\"\xd6\x01\n" +
	"\x0fProductMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x04R\x05price\x12\x19\n" +
	"\x05stock\x18\x05 \x01(\x04H\x00R\x05stock\x88\x01\x01\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\x04R\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"main_image\x18\a \x01(\fR\tmainImageB\b\n" +
	"\x06_stock\"$\n" +
	"\fGalleryImage\x12\x14\n" +
	"\x05image\x18\x01 \x01(\fR\x05image\"\x81\x01\n" +
	"\rCreateRequest\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.product.ProductMetadataH\x00R\bmetadata\x12-\n" +
	"\x05image\x18\x02 \x01(\v2\x15.product.GalleryImageH\x00R\x05imageB\t\n" +
	"\apayload\"\xef\x01\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x04R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x04R\x05stock\x12\x1f\n" +
	"\vcategory_id\x18\a \x01(\x04R\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"main_image\x18\b \x01(\tR\tmainImage\x12\x16\n" +
	"\x06images\x18\t \x03(\tR\x06images\"u\n" +
	"\rGetAllRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12(\n" +
	"\rcategory_slug\x18\x03 \x01(\tH\x00R\fcategorySlug\x88\x01\x01B\x10\n" +
	"\x0e_category_slug\"\xb5\x01\n" +
	"\x0fProductListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x04R\x05price\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\x04R\x05stock\x12\x1f\n" +
	"\vcategory_id\x18\x06 \x01(\x04R\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"main_image\x18\a \x01(\tR\tmainImage\"q\n" +
	"\x0ePaginationMeta\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\"s\n" +
	"\x0eGetAllResponse\x124\n" +
	"\bproducts\x18\x01 \x03(\v2\x18.product.ProductListItemR\bproducts\x12+\n" +
	"\x04meta\x18\x02 \x01(\v2\x17.product.PaginationMetaR\x04meta\")\n" +
	"\x13GetOneBySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug2\xd1\x01\n" +
	"\x0eProductService\x12<\n" +
	"\x06Create\x12\x16.product.CreateRequest\x1a\x18.product.ProductResponse(\x01\x129\n" +
	"\x06GetAll\x12\x16.product.GetAllRequest\x1a\x17.product.GetAllResponse\x12F\n" +
	"\fGetOneBySlug\x12\x1c.product.GetOneBySlugRequest\x1a\x18.product.ProductResponseB\x1aZ\x18shop/internal/pb/productb\x06proto3"

var (
	file_product_product_proto_rawDescOnce sync.Once
	file_product_product_proto_rawDescData []byte
)

func file_product_product_proto_rawDescGZIP() []byte {
	file_product_product_proto_rawDescOnce.Do(func() {
		file_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_product_proto_rawDesc), len(file_product_product_proto_rawDesc)))
	})
	return file_product_product_proto_rawDescData
}

var file_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_product_product_proto_goTypes = []any{
	(*ProductMetadata)(nil),     // 0: product.ProductMetadata
	(*GalleryImage)(nil),        // 1: product.GalleryImage
	(*CreateRequest)(nil),       // 2: product.CreateRequest
	(*ProductResponse)(nil),     // 3: product.ProductResponse
	(*GetAllRequest)(nil),       // 4: product.GetAllRequest
	(*ProductListItem)(nil),     // 5: product.ProductListItem
	(*PaginationMeta)(nil),      // 6: product.PaginationMeta
	(*GetAllResponse)(nil),      // 7: product.GetAllResponse
	(*GetOneBySlugRequest)(nil), // 8: product.GetOneBySlugRequest
}
var file_product_product_proto_depIdxs = []int32{
	0, // 0: product.CreateRequest.metadata:type_name -> product.ProductMetadata
	1, // 1: product.CreateRequest.image:type_name -> product.GalleryImage
	5, // 2: product.GetAllResponse.products:type_name -> product.ProductListItem
	6, // 3: product.GetAllResponse.meta:type_name -> product.PaginationMeta
	2, // 4: product.ProductService.Create:input_type -> product.CreateRequest
	4, // 5: product.ProductService.GetAll:input_type -> product.GetAllRequest
	8, // 6: product.ProductService.GetOneBySlug:input_type -> product.GetOneBySlugRequest
	3, // 7: product.ProductService.Create:output_type -> product.ProductResponse
	7, // 8: product.ProductService.GetAll:output_type -> product.GetAllResponse
	3, // 9: product.ProductService.GetOneBySlug:output_type -> product.ProductResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_product_product_proto_init() }
func file_product_product_proto_init() {
	if File_product_product_proto != nil {
		return
	}
	file_product_product_proto_msgTypes[0].OneofWrappers = []any{}
	file_product_product_proto_msgTypes[2].OneofWrappers = []any{
		(*CreateRequest_Metadata)(nil),
		(*CreateRequest_Image)(nil),
	}
	file_product_product_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_product_proto_rawDesc), len(file_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_product_proto_goTypes,
		DependencyIndexes: file_product_product_proto_depIdxs,
		MessageInfos:      file_product_product_proto_msgTypes,
	}.Build()
	File_product_product_proto = out.File
	file_product_product_proto_goTypes = nil
	file_product_product_proto_depIdxs = nil
}
