// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: province/province.proto

package province

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvinceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvinceResponse) Reset() {
	*x = ProvinceResponse{}
	mi := &file_province_province_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvinceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvinceResponse) ProtoMessage() {}

func (x *ProvinceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_province_province_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvinceResponse.ProtoReflect.Descriptor instead.
func (*ProvinceResponse) Descriptor() ([]byte, []int) {
	return file_province_province_proto_rawDescGZIP(), []int{0}
}

func (x *ProvinceResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProvinceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_province_province_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_province_province_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_province_province_proto_rawDescGZIP(), []int{1}
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provinces     []*ProvinceResponse    `protobuf:"bytes,1,rep,name=provinces,proto3" json:"provinces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_province_province_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_province_province_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_province_province_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllResponse) GetProvinces() []*ProvinceResponse {
	if x != nil {
		return x.Provinces
	}
	return nil
}

type GetOneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOneRequest) Reset() {
	*x = GetOneRequest{}
	mi := &file_province_province_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOneRequest) ProtoMessage() {}

func (x *GetOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_province_province_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOneRequest.ProtoReflect.Descriptor instead.
func (*GetOneRequest) Descriptor() ([]byte, []int) {
	return file_province_province_proto_rawDescGZIP(), []int{3}
}

func (x *GetOneRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_province_province_proto protoreflect.FileDescriptor

const file_province_province_proto_rawDesc = "" +
	"\n" +
	"\x17province/province.proto\x12\bprovince\"6\n" +
	"\x10ProvinceResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x0f\n" +
	"\rGetAllRequest\"J\n" +
	"\x0eGetAllResponse\x128\n" +
	"\tprovinces\x18\x01 \x03(\v2\x1a.province.ProvinceResponseR\tprovinces\"\x1f\n" +
	"\rGetOneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id2\x8d\x01\n" +
	"\x0fProvinceService\x12;\n" +
	"\x06GetAll\x12\x17.province.GetAllRequest\x1a\x18.province.GetAllResponse\x12=\n" +
	"\x06GetOne\x12\x17.province.GetOneRequest\x1a\x1a.province.ProvinceResponseB\x1bZ\x19shop/internal/pb/provinceb\x06proto3"

var (
	file_province_province_proto_rawDescOnce sync.Once
	file_province_province_proto_rawDescData []byte
)

func file_province_province_proto_rawDescGZIP() []byte {
	file_province_province_proto_rawDescOnce.Do(func() {
		file_province_province_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_province_province_proto_rawDesc), len(file_province_province_proto_rawDesc)))
	})
	return file_province_province_proto_rawDescData
}

var file_province_province_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_province_province_proto_goTypes = []any{
	(*ProvinceResponse)(nil), // 0: province.ProvinceResponse
	(*GetAllRequest)(nil),    // 1: province.GetAllRequest
	(*GetAllResponse)(nil),   // 2: province.GetAllResponse
	(*GetOneRequest)(nil),    // 3: province.GetOneRequest
}
var file_province_province_proto_depIdxs = []int32{
	0, // 0: province.GetAllResponse.provinces:type_name -> province.ProvinceResponse
	1, // 1: province.ProvinceService.GetAll:input_type -> province.GetAllRequest
	3, // 2: province.ProvinceService.GetOne:input_type -> province.GetOneRequest
	2, // 3: province.ProvinceService.GetAll:output_type -> province.GetAllResponse
	0, // 4: province.ProvinceService.GetOne:output_type -> province.ProvinceResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_province_province_proto_init() }
func file_province_province_proto_init() {
	if File_province_province_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_province_province_proto_rawDesc), len(file_province_province_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_province_province_proto_goTypes,
		DependencyIndexes: file_province_province_proto_depIdxs,
		MessageInfos:      file_province_province_proto_msgTypes,
	}.Build()
	File_province_province_proto = out.File
	file_province_province_proto_goTypes = nil
	file_province_province_proto_depIdxs = nil
}
